export const country = [
  
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "AZ",
    name: "أذربيج,ان",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "AM",
    name: "أرميني,ا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "ES",
    name: "أسباني,ا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "AU",
    name: "أسترال,يا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "AF",
    name: "أفغانس,تان",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "AL",
    name: "ألباني,ا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "DE",
    name: "ألماني,ا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "AG",
    name: "أنتيجو,ا وبربودا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "AO",
    name: "أنجولا,",
  },
 
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "AD",
    name: "أندورا,",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "UY",
    name: "أورجوا,ي",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "UZ",
    name: "أوزبكس,تان",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "UG",
    name: "أوغندا,",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "UA",
    name: "أوكران,يا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "IE",
    name: "أيرلند,ا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "IS",
    name: "أيسلند,ا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "ET",
    name: "اثيوبي,ا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "ER",
    name: "اريتري,ا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "EE",
    name: "استوني,ا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "IL",
    name: "اسرائي,ل",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "AR",
    name: "الأرجن,تين",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "JO",
    name: "الأردن,",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "EC",
    name: "الاكوا,دور",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "AE",
    name: "الامار,ات العربية المتحدة",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "BS",
    name: "الباها,ما",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "BH",
    name: "البحري,ن",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "BR",
    name: "البراز,يل",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "PT",
    name: "البرتغ,ال",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "BA",
    name: "البوسن,ة والهرسك",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "GA",
    name: "الجابو,ن",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "ME",
    name: "الجبل ,الأسود",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "DZ",
    name: "الجزائ,ر",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "DK",
    name: "الدانم,رك",
  },
 
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "SV",
    name: "السلفا,دور",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "SN",
    name: "السنغا,ل",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "SD",
    name: "السودا,ن",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "SE",
    name: "السويد,",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "EH",
    name: "الصحرا,ء الغربية",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "SO",
    name: "الصوما,ل",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "CN",
    name: "الصين",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "IQ",
    name: "العراق,",
  },

  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "PH",
    name: "الفيلب,ين",
  },

  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "CM",
    name: "الكامي,رون",
  },

  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "KW",
    name: "الكويت,",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "HU",
    name: "المجر",
  },
 
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "MA",
    name: "المغرب,",
  },

  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "MX",
    name: "المكسي,ك",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "SA",
    name: "المملك,ة العربية السعودية",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "GB",
    name: "المملك,ة المتحدة",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "NO",
    name: "النروي,ج",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "AT",
    name: "النمسا,",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "NE",
    name: "النيجر,",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "IN",
    name: "الهند",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "US",
    name: "الولاي,ات المتحدة الأمريكية",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "JP",
    name: "اليابا,ن",
  },

  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "GR",
    name: "اليونا,ن",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "ID",
    name: "اندوني,سيا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "IR",
    name: "ايران",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "IT",
    name: "ايطالي,ا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "PG",
    name: "بابوا ,غينيا الجديدة",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "PY",
    name: "باراجو,اي",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "PK",
    name: "باكستا,ن",
  },
  
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "BW",
    name: "بتسوان,ا",
  },
  
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "BB",
    name: "بربادو,س",
  },

  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "BE",
    name: "بلجيكا,",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "BG",
    name: "بلغاري,ا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "BZ",
    name: "بليز",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "BD",
    name: "بنجلاد,يش",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "PA",
    name: "بنما",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "BJ",
    name: "بنين",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "BT",
    name: "بوتان",
  },

  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "BF",
    name: "بوركين,ا فاسو",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "BI",
    name: "بوروند,ي",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "PL",
    name: "بولندا,",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "BO",
    name: "بوليفي,ا",
  },

  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "PE",
    name: "بيرو",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "TZ",
    name: "تانزان,يا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "TH",
    name: "تايلند,",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "TW",
    name: "تايوان,",
  },
  
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "TR",
    name: "تركيا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "TT",
    name: "ترينيد,اد وتوباغو",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "TD",
    name: "تشاد",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "TG",
    name: "توجو",
  },
 

 
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "TN",
    name: "تونس",
  },
 
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "JM",
    name: "جامايك,ا",
  },

  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "GD",
    name: "جريناد,ا",
  },

 

  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "MV",
    name: "جزر ال,ملديف",
  },
  
 

 
 
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "CF",
    name: "جمهوري,ة افريقيا الوسطى",
  },

  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "DO",
    name: "جمهوري,ة الدومينيك",
  },
 
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "ZA",
    name: "جمهوري,ة جنوب افريقيا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "GT",
    name: "جواتيم,الا",
  },
  

  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "GE",
    name: "جورجيا,",
  },

  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "DJ",
    name: "جيبوتي,",
  },
 
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "DM",
    name: "دوميني,كا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "RW",
    name: "رواندا,",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "RU",
    name: "روسيا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "BY",
    name: "روسيا ,البيضاء",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "RO",
    name: "روماني,ا",
  },
 
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "ZM",
    name: "زامبيا,",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "ZW",
    name: "زيمباب,وي",
  },



  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "SM",
    name: "سان ما,رينو",
  },

  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "VC",
    name: "سانت ف,نسنت وغرنادين",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "KN",
    name: "سانت ك,يتس ونيفيس",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "LC",
    name: "سانت ل,وسيا",
  },
 
 
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "LK",
    name: "سريلان,كا",
  },
  
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "SK",
    name: "سلوفاك,يا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "SI",
    name: "سلوفين,يا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "SG",
    name: "سنغافو,رة",
  },

  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "SY",
    name: "سوريا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "SR",
    name: "سورينا,م",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "CH",
    name: "سويسرا,",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "SL",
    name: "سيرالي,ون",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "SC",
    name: "سيشل",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "CL",
    name: "شيلي",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "RS",
    name: "صربيا",
  },

  
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "OM",
    name: "عمان",
  },
 
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "GH",
    name: "غانا",
  },

  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "GY",
    name: "غيانا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "GN",
    name: "غينيا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "GQ",
    name: "غينيا ,الاستوائية",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "GW",
    name: "غينيا ,بيساو",
  },
  
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "FR",
    name: "فرنسا",
  },

  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "VE",
    name: "فنزويل,ا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "FI",
    name: "فنلندا,",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "VN",
    name: "فيتنام,",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "FJ",
    name: "فيجي",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "CY",
    name: "قبرص",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "KG",
    name: "قرغيزس,تان",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "QA",
    name: "قطر",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "KZ",
    name: "كازاخس,تان",
  },

  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "HR",
    name: "كرواتي,ا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "KH",
    name: "كمبودي,ا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "CA",
    name: "كندا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "CU",
    name: "كوبا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "KR",
    name: "كوريا ,الجنوبية",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "KP",
    name: "كوريا ,الشمالية",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "CR",
    name: "كوستار,يكا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "CO",
    name: "كولومب,يا",
  },
 
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "KE",
    name: "كينيا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "LV",
    name: "لاتفيا,",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "LA",
    name: "لاوس",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "LB",
    name: "لبنان",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "LU",
    name: "لوكسمب,ورج",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "LY",
    name: "ليبيا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "LR",
    name: "ليبيري,ا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "LT",
    name: "ليتوان,يا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "LI",
    name: "ليختنش,تاين",
  },
  
 
 
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "MT",
    name: "مالطا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "ML",
    name: "مالي",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "MY",
    name: "ماليزي,ا",
  },

  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "MG",
    name: "مدغشقر,",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "EG",
    name: "مصر",
  },

  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "MW",
    name: "ملاوي",
  },
  
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "MN",
    name: "منغولي,ا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "MR",
    name: "موريتا,نيا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "MU",
    name: "موريشي,وس",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "MZ",
    name: "موزمبي,ق",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "MD",
    name: "مولداف,يا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "MC",
    name: "موناكو,",
  },
 
 
 
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "NA",
    name: "ناميبي,ا",
  },
  
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "NP",
    name: "نيبال",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "NG",
    name: "نيجيري,ا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "NI",
    name: "نيكارا,جوا",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "NZ",
    name: "نيوزيل,اندا",
  },
  
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "HT",
    name: "هايتي",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "HN",
    name: "هندورا,س",
  },
  {
    lastUpdate: 0,
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    code: "NL",
    name: "هولندا,",
  },
 
];
